spring:
  application:
    name: ems
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: myuser
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
logging:
  level:
    org.springframework.web: DEBUG
    com.mavene.ems.controller: DEBUG
